### ISSUE TITLE
Missing method exception when working with NBomber 4.x.x

### ISSUE THREAD

**Issue by mlschneid** [PragmaticFlow/NBomber.Sinks.InfluxDB#12]
When running a small sample app that targets NBomber 4.0.0-rc and relies on NBomber.Sinks.InfluxDB, the following exception is captured in the logs within the /report folder.

```2023-01-17 14:51:10.580 -08:00 [FTL] [ThreadId:7] Reporting sink: NBomber.Sinks.InfluxDB failed to save scenario stats
System.MissingMethodException: Method not found: 'NBomber.Contracts.Stats.StepStatsData NBomber.Contracts.Stats.StepStats.get_Ok()'.
   at NBomber.Sinks.InfluxDB.InfluxDBSink.mapScenarioStats(IBaseContext context, CustomTag[] tags, ScenarioStats scnStats)
   at <StartupCode$NBomber-Sinks-InfluxDB>.$InfluxDBSink.writeRealtimeStats@187.Invoke(ScenarioStats scnStats)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array) in D:\a\_work\1\s\src\FSharp.Core\array.fs:line 148
   at <StartupCode$NBomber-Sinks-InfluxDB>.$InfluxDBSink.NBomber-Contracts-IReportingSink-SaveRealtimeStats@182.Invoke(InfluxDBClient client)
   at NBomber.Sinks.InfluxDB.InfluxDBSink.NBomber.Contracts.IReportingSink.SaveRealtimeStats(ScenarioStats[] stats)
   at NBomber.DomainServices.TestHost.ReportingSinks.saveRealtimeStats@39.MoveNext()
```

I think there needs to be a 4.0.0-rc of this package released as well.

**Comment by AntyaDev** [comment]
Hi @mlschneid ,

Yes, you are right.
I hope this week it will be released.

**Comment by AntyaDev** [comment]
Fixed
https://github.com/PragmaticFlow/NBomber.Sinks.InfluxDB/commit/17e06dc3352b3db8330922ed753d9981108bf7b9
